export const masterWordBank = {
  pooped_message: [
    "Good Job",
    "The paperwork has cleared.",
    "Another throne session enters the history books.",
    "Humanity thanks you for your service.",
    "A bold performance with very little fanfare.",
    "You did what had to be done.",
    "A quiet victory for plumbing everywhere.",
    "The mission report reads: successful exit.",
    "A respectable effort with a strong finish.",
    "The chamber of consequences is now at peace.",
    "Your ancestors would call this solid work.",
    "The bowl has accepted your offering.",
    "A clean decision was made today.",
    "Heroic behavior in a very small room.",
    "That was weirdly professional.",
    "You showed up. Nature handled the rest.",
    "The porcelain committee approves.",
    "A modest miracle has occurred.",
    "Another burden has left the kingdom.",
    "The vibes in the bathroom just improved.",
    "Efficiency like this deserves a slow clap.",
    "The seal is broken. The spirit is lighter.",
    "No notes. Just relief.",
    "A legendary sit with a practical ending.",
    "The tension has officially resigned.",
    "That was a strong closing argument.",
    "Even the exhaust fan is impressed.",
    "This will not be taught in schools, but it should be.",
    "A private win is still a win.",
    "You have restored balance to the household.",
    "The log has been logged. Bureaucracy loves that.",
    "That was brave, necessary, and a little dramatic.",
    "The bathroom stocks are up.",
    "A deeply unglamorous triumph.",
    "The throne room salutes you.",
    "Excellent release management.",
    "A moving experience, literally.",
    "The afterglow is well earned.",
    "That was cleaner than your last email.",
    "You conquered the urge to give up too early.",
    "The pipes may speak of this day.",
    "A premium performance under seated conditions.",
    "This one goes on the highlight reel.",
    "Your lower abdomen sends its regards.",
    "Grace under pressure, then less pressure.",
    "You did not fold. You flushed.",
    "A tasteful display of perseverance.",
    "The bowl witnessed greatness.",
    "One small sit for you, one giant relief for mankind.",
    "The universe is lighter by one concern.",
  ],
  fake_user_feed: {
    early: ["seat's still cold", "stall check-in", "phone at 12%"],
    middle: ["false alarm", "we're negotiating", "this is all paperwork"],
    push: ["LOCK IN", "OH WOW", "THIS IS IT"],
    victory: ["light as air", "worth the wait", "goodbye old self"],
  },
} as const;
